[package]
name = "serial_display"
version = "0.1.0"
authors = ["Niels Majer <niels.majer@gmail.com"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
serialport = "3.3"
actix = "0.8"
actix-codec = "0.1"
actix-web = "1.0"
actix-web-actors = "1.0"
actix-files = "0.1"
rand = "0.7"
